server:
  port: 8080

#默认使用配置
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.hxf.mall.bean
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/xmall?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
      maxFileSize: 2048MB #单个文件大小
      maxRequestSize: 2048MB  #总上传文件大小

#设置静态资源路径，多个以逗号分隔
  resources:
    static-locations:
      - classpath:static/
      - file:static/

qiniu:
  access:
    key: LEkt-mgrsIoHcSqJbGm3fEIuWOPv1_BKlXXoobGw
  secret:
    key: T2nwr0E9ZJPJ5TH-k-j8WL3SGGT1oWXntTiLihK1
  bucket:
    name: mymall
    host:
      name: http://poe12lctf.bkt.clouddn.com
